"""Add SET NULL on delete for books id_author

Revision ID: 4b8f45f700b8
Revises: e3595be60515
Create Date: 2025-01-16 01:07:12.425774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8f45f700b8'
down_revision: Union[str, None] = 'e3595be60515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'id_author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('books_id_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['id_author'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_id_author_fkey', 'books', 'authors', ['id_author'], ['id'])
    op.alter_column('books', 'id_author',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
