"""Add cascaded

Revision ID: 5ddd97fabd6a
Revises: e751c60f2dba
Create Date: 2025-01-16 00:50:30.096253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddd97fabd6a'
down_revision: Union[str, None] = 'e751c60f2dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_id_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['id_author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_id_author_fkey', 'books', 'authors', ['id_author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
