"""Add casced to books table

Revision ID: 6f4d83643b6c
Revises: 09111238376e
Create Date: 2025-01-15 23:58:55.252566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4d83643b6c'
down_revision: Union[str, None] = '09111238376e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_id_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['id_author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_id_author_fkey', 'books', 'authors', ['id_author'], ['id'])
    # ### end Alembic commands ###
