"""Add cascade delete for authors in books

Revision ID: bc6a06743585
Revises: 4b8f45f700b8
Create Date: 2025-01-18 01:40:22.428249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6a06743585'
down_revision: Union[str, None] = '4b8f45f700b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_id_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['id_author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_id_author_fkey', 'books', 'authors', ['id_author'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
